apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
mirror:
  ocp:
    channels:
      - name: stable-4.10
# Uncomment out below to specify operators to be mirrored
#        - name: local-storage-operator
#          channels:
#          - name: latest
#        - name: local-storage-operator
#          channels:
#          - name: latest
#        - name: local-storage-operator
#          channels:
#          - name: latest
